# METHODS

## SURVEY LOCATIONS

Fishing (Figure \@ref(fig:mapfish)), oceanographic and zooplankton sampling (Figure \@ref(fig:mapctd)) occurred `r surveyRegion`, including Johnstone Strait, Queen Charlotte Strait, Queen Charlotte Sound, and mainland British Columbia inlets. 

## FISHING OPERATIONS

The vessel deployed a coastal LFS 7742 trawl net (Appendix \@ref(app:appNet), manufactured by [LFS Trawl](https://www.lfsinc.com/commericalfishinggear/trawl.htm) (LFS Net Systems, Bellingham, USA). This two-bridle mid-water net has a codend liner (6.35 mm mesh) to retain smaller species. The coastal LFS 7742 trawl net was designed to have a net opening of 30 m wide by 15 m high, or an area of 450 m^2^ (Figure \@ref(fig:coastalnet)). Actual net openings varied and tended to be larger than expected; therefore, height and width dimensions were recorded for each tow and used in the calculation of catch per swept volume (Figures \@ref(fig:pkcpue) to \@ref(fig:cocpue)). 

The net was fished with [Thyborøn](https://thyboron-trawldoor.dk/) Type 15 VF, 4.5 m^2^ mid water doors (approximately 730 kg each). Two chain clumps were attached to the footrope with approximately 160 kg (350 lbs) per chain clump. The vessel was equipped with a [Marport](https://www.marport.com/index.html) Trawl System and wireless Marport Trawleye that provided realtime doorspread, headline depth and net opening values (Marport Americas Inc., Washington, USA). In addition, [RBR duet temperature and depth sensors](https://rbr-global.com/products/compact-loggers/rbrduet-td) (RBR Ltd., Ottawa, ON, Canada) were attached to the headrope and footrope to record depth every 30 seconds. The vertical net opening was plotted over time to show the net opening and depth.

Tow speed varied between `r min(bridgetow_orig$SPEED_KM, na.rm = TRUE)` to `r max(bridgetow_orig$SPEED_KM, na.rm = TRUE)` km/hour (`r min(bridgetow_orig$SPEED_NM, na.rm = TRUE)` and `r max(bridgetow_orig$SPEED_NM, na.rm = TRUE)` knots) speed over ground, depending on the wind, tide, and current, in order to reach the target headrope depth. The target headrope depths were 0 m (surface) and 15 m (depth). Two A-6 floats 86.4 cm x 118.1 cm (34" x 46.5") were attached to the on headrope for surface tows. Warp length ranged from `r min(bridgetow_orig$WARP, na.rm = TRUE)`m to `r max(bridgetow_orig$WARP, na.rm = TRUE)`m (Appendix \@ref(app:appBridge)). Target tow duration was 15-20 min once the trawls doors were locked and the net fishing.

## BIOLOGICAL SAMPLES
Species were sorted by species or taxonomic group (Figure \@ref(fig:photo)), then the individuals measured for length and weight. Stomachs were analysed at sea following an established protocol [@king2018]. For each species in the tow, up to five whole bodies and five muscle tissues were collected for energy density and stable isotope analyses. Additional collection for Pacific Salmon species included: fin clips for genetic stock identification, otoliths, and adipose fin status, and coded wire tags (CWTs).

## OCEANOGRAPHY
A standalone [Sea-bird](https://www.seabird.com/) 25 CTD (conductivity-temperature-depth) was used for water profiles (Sea-bird Electronics Bellevue Washington, USA) at `r nrow(ctdSimp)` stations (Figure \@ref(fig:mapctd), Appendix \@ref(app:appOcean)). A Niskin bottle at 10 m from the surface was used for chlorophyll (chl a) and nutrient collections. Seawater samples for nitrate, phosphate, and silicate were placed in acid-washed glass test tubes and frozen. Seawater for chl a estimation were filtered with GF/F glass fibre filter disks. Filter disks were then placed in polypropylene scintillation vials and frozen. Both the chlorophyll and nutrient samples were frozen and maintained at -18&deg;C. Seawater and chl a samples were sent for analyses at the Institute of Ocean Sciences, Fisheries and Oceans Canada (Sidney, BC). 


## ZOOPLANKTON
At `r nrow(planktonSimp)` zooplankton stations (Figure \@ref(fig:mapctd), Appendix \@ref(app:appOcean)), vertical tows were conducted to approximately 250 m or within 10 m of the bottom with two 60 cm diameter, 253 micrometer mesh nets mounted in a bongo-drum style frame. Zooplankton collected from the flow meter side were preserved in 10% formalin and sent to the zooplankton laboratory at the Institute of Ocean Sciences, Fisheries and Oceans Canada (Sidney, BC) for species classification and enumeration. The remaining zooplankton sample was sorted into four size fractions by successively sieving through 8.0, 1.7, 1.0, and 0.25 mm screens. Individual size fractions were frozen for future stable isotope, energy density, and proximate analyses.

## ACOUSTIC DATA
Acoustic data was collected throughout the survey using the vessel [SIMRAD](https://www.kongsberg.com/maritime/products/commercial-fisheries/echo-sounders/) ES60 echo sounder (Kongsberg Maritime CM Canada Lid, Vancouver, Canada).
