# DISCUSSION

This ecosystem-based juvenile Pacific Salmon survey collected valuable information on distribution, abundance, condition, and genetic stock composition (GSI) for juvenile Pacific Salmon `r surveyRegion`. Overall, juvenile Pink Salmon and Chum Salmon and were most abundant, whereas Coho Salmon were least abundant. Distributions and stomach contents varied by species. The most abundant prey species were amphiipods, euphausiids, and Pacific Herring, depending on the predator species. We collected `r nrow(ctd_orig)` physical oceanographic water profiles, and `r nrow(planktonvert)` zooplankton samples associated with the Pacific Salmon caught. Select data from laboratory analysis (i.e. GSI, energy density) has been completed and will integrated into the survey data. Other items are awaiting analysis (i.e. zooplankton composition, isotopic analysis). These catch data, along with condition and GSI data, supplement historic juvenile Pacific Salmon surveys and have been reported in Fisheries and Oceans Canada [State of the Pacific Ocean](https://dfo-mpo.gc.ca/oceans/publications/index-eng.html#soto-pac-tech) report and incorporated into larger research projects. 
