---
title: "Ecosystem-Based Juvenile Pacific Salmon (*Oncorhynchus* spp.) Survey off North East Vancouver Island, British Columbia, September 30 - October 8, 2019"
year: 2021
report_number: nnnn
author: |
  Erika D. Anderson,
  Jackie R. King, and
  Tyler B. Zubkowski
author_list: "Anderson, E.D., King, J.R. and Zubkowski, T.B."
region: Pacific Region
isbn: "xxxx"
address: |
  Pacific Biological Station\
  Fisheries and Oceans Canada, 3190 Hammond Bay Road\
  Nanaimo, British Columbia, V9T 6N7, Canada\
phone: "(250) 756-7067"
author_footnote: "Email: Erika.Anderson@dfo-mpo.gc.ca | telephone: (250) 756-7067"
abstract: |
  Here is the abstract text. 
  
abstract_other: |
  Voici le résumé. 
  
output:
 csasdown::techreport_word:
   french: false
   copy_sty: false
   line_nums: true
   line_nums_mod: 1
type:
  techreport
# ------------
# End of options to set
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
csl: csl/csas.csl
lot: true
lof: true
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  cache = FALSE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(xtable.comment = FALSE)
options(kableExtra.latex.load_packages = FALSE)

# EA added the options below

# hide NAs within tables
  options(knitr.kable.NA = '')

# turn off significant figures
  options(scipen = 999)
  
```

```{r load-libraries, cache=FALSE}
# `french` and `prepub` variables are extracted from the YAML headers above and
#  are used throughout the document. To make the document all in french, change
#  the line in the YAML header above to `french: true`
meta <- rmarkdown::metadata$output
if (length(grep("pdf", names(meta)))) {
  french <- meta$`csasdown::techreport_pdf`$french
  prepub <- meta$`csasdown::techreport_pdf`$prepub
} else if (length(grep("word", names(meta)))) {
  french <- meta$`csasdown::techreport_word`$french
  prepub <- meta$`csasdown::techreport_word`$prepub
}

# add other packages here:
library(tidyverse)
library(csasdown)
library(car) # statistics
library(RODBC) # database connection
library(lubridate) # functions with dates
library(cowplot) # multiple plots in one
library(float) # fix the table-page breaks
library(broom) # display linear model on LW graphs easily
library(xfun) # to convert numeric values to text
library(celestial) #to convert lat/lon values
#library(openxlsx) # load excel data
library(rgdal) # to load shapefiles
library(naniar) # function replace_with_na
library(kableExtra) # better table layouts


```

```{r surveyDetails}

# *** survey number 
# note the extra quotes are needed
CRUISEchr <- "'2019125'"
CRUISEnum <- 2019125

surveyName <- "ecosystem-based juvenile Pacific Salmon survey"

surveyDateRange <- "September 30 to October 8, 2019"

surveyYear <- "2019"

vessel <- "CFV Sea Crest"

```

```{r locations}

# location data for maps from bridge data for fishing tows
# use sql 2019125_tows_orig: SELECT BRIDGE_COMPLETE.CRUISE, BRIDGE_COMPLETE.STATION_ID, BRIDGE_COMPLETE.EVENT, BRIDGE_COMPLETE.STATION, BRIDGE_COMPLETE.YEAR, BRIDGE_COMPLETE.MONTH, BRIDGE_COMPLETE.DAY, BRIDGE_COMPLETE.UNUSABLE, BRIDGE_COMPLETE.START_TIME, BRIDGE_COMPLETE.START_LAT, BRIDGE_COMPLETE.START_LONG, BRIDGE_COMPLETE.END_LAT, BRIDGE_COMPLETE.END_LONG, BRIDGE_COMPLETE.DISTANCE, BRIDGE_COMPLETE.DUR, BRIDGE_COMPLETE.[SOG-KTS], BRIDGE_COMPLETE.HEADING, BRIDGE_COMPLETE.START_BOT_DEPTH, BRIDGE_COMPLETE.END_BOT_DEPTH, BRIDGE_COMPLETE.NET_OPENING_WIDTH, BRIDGE_COMPLETE.NET_OPENING_HEIGHT, BRIDGE_COMPLETE.HEAD_DEPTH, BRIDGE_COMPLETE.WARP, BRIDGE_COMPLETE.GEAR FROM BRIDGE_COMPLETE WHERE (((BRIDGE_COMPLETE.CRUISE)="2019125"));

# load as csv
tows_orig <- readr::read_csv("data/csv/2019125_tows_orig.csv",
                             col_types = 
                               cols(
                               CRUISE = col_double(),
                               STATION_ID = col_character(),
                               EVENT = col_double(),
                               STATION = col_character(),
                               YEAR = col_double(),
                               MONTH = col_character(),
                               DAY = col_double(),
                               UNUSABLE = col_logical(),
                               START_TIME = col_character(),
                               START_LAT = col_double(),
                               START_LONG = col_double(),
                               END_LAT = col_double(),
                               END_LONG = col_double(),
                               DISTANCE = col_double(),
                               DUR = col_double(),
                               `SOG-KTS` = col_double(),
                               HEADING = col_double(),
                               START_BOT_DEPTH = col_double(),
                               END_BOT_DEPTH = col_double(),
                               NET_OPENING_WIDTH = col_double(),
                               NET_OPENING_HEIGHT = col_double(),
                               HEAD_DEPTH = col_double(),
                               WARP = col_double(),
                               GEAR = col_character()
                               ))

# location data for CTD casts from OCEAN_CTD table
# sql 2019125_ctd_orig
# SELECT BRIDGE_COMPLETE.CRUISE, OCEAN_CTD.STATION_ID, OCEAN_CTD.EVENT, OCEAN_CTD.STATION, OCEAN_CTD.CTD_INSTRUMENT, OCEAN_CTD.CTD_SERIAL_NUMBER, OCEAN_CTD.DATE_UTC, OCEAN_CTD.TIME_UTC, OCEAN_CTD.CTD_LAT, OCEAN_CTD.CTD_LONG, OCEAN_CTD.BOTTOM_DEPTH, OCEAN_CTD.CTD_DEPTH
# FROM OCEAN_CTD INNER JOIN BRIDGE_COMPLETE ON OCEAN_CTD.STATION_ID = BRIDGE_COMPLETE.STATION_ID
# WHERE (((BRIDGE_COMPLETE.CRUISE)="2019125"));

# # load as csv
ctd_orig <- readr::read_csv("data/csv/2019125_ctd_orig.csv")

ctdSimp <- ctd_orig %>%
  mutate(EVENT_TYPE = "ctd",
         LAT = CTD_LAT,
         LONG = CTD_LONG) %>%
  select(EVENT_TYPE, LAT, LONG)

# location data for vertical plankton tows from PLANKTON table
# sql
# # load as csv
plankton_orig <- readr::read_csv("data/csv/2019125_plankton_orig.csv")

planktonSimp <- plankton_orig %>%
  mutate(EVENT_TYPE = "bongo",
         LAT = BONGO_LAT,
         LONG = BONGO_LONG) %>%
  select(EVENT_TYPE, LAT, LONG)

# combine ctd and plankton data for map
ocean <- rbind(ctdSimp, planktonSimp)

# wrangle tow data
tows <- tows_orig %>%
  mutate(DATE = ymd(str_c(YEAR, MONTH, DAY, sep = "-")),
         TARGET_DEPTH = as.factor(HEAD_DEPTH)) 

# find min and max lat and longs for limits to basemap
minLat <- min(tows$START_LAT) - 0.5
maxLat <- max(tows$START_LAT) + 0.5
minLon <- min(tows$START_LONG) - 0.5
maxLon <- max(tows$START_LONG) + 0.5

# load basemap from coastal shapefile
coast <- readOGR("data/Spatial/Land.shp", verbose = FALSE)

# basemap
  basemap <- ggplot() +
    geom_path(data = coast, aes(x = long, y = lat, group = group)) +
    coord_equal() +
    xlim(minLon, maxLon) +
    ylim(minLat, maxLat) +
    labs(x = "Longitude",
         y = "Laititude") +
    theme_bw()

```

```{r net}

net <- tows %>%
  summarize(Vertavg = round(mean(NET_OPENING_HEIGHT),0),
            Vertmin = min(NET_OPENING_HEIGHT),
            Vertmax = max(NET_OPENING_HEIGHT),
            Horavg = round(mean(NET_OPENING_WIDTH), 0),
            Hormin = min(NET_OPENING_WIDTH),
            Hormax = max(NET_OPENING_WIDTH), .groups = "drop")

```

```{r salmon}

# # sql query
# SELECT CRUISE_INFO.CRUISE, BRIDGE.EVENT, BRIDGE.Year, BRIDGE.Month, BRIDGE.Day, BRIDGE.Date, BRIDGE.START_LAT, BRIDGE.START_LONG, BRIDGE.DISTANCE, BRIDGE.NET_OPENING_WIDTH, BRIDGE.NET_OPENING_HEIGHT, BRIDGE.HEAD_DEPTH, BRIDGE.[ESTIMATED_CATCHES_ BY_WT], BRIDGE.PK_JUV, BRIDGE.CM_JUV, BRIDGE.CM_ADULT, BRIDGE.SE_JUV, BRIDGE.CO_JUV, BRIDGE.CK_JUV, BRIDGE.GEAR_TYPE, BRIDGE.COMMENTS
# FROM (CRUISE_INFO INNER JOIN STATION_INFO ON CRUISE_INFO.CRUISE = STATION_INFO.CRUISE) INNER JOIN BRIDGE ON STATION_INFO.STATION_ID = BRIDGE.STATION_ID
# WHERE (((CRUISE_INFO.CRUISE)='2019125'));

salmondf_orig <- readr::read_csv("data/csv/2019125_salmondf_orig.csv",
                                 col_types = cols(
                CRUISE = col_double(),
                CRUISE = col_double(),
                EVENT = col_double(),
                Year = col_double(),
                Month = col_character(),
                Day = col_double(),
                # MS Access and R date format conflict
                Date = col_character(), 
                START_LAT = col_double(),
                START_LONG = col_double(),
                DISTANCE = col_double(),
                NET_OPENING_WIDTH = col_double(),
                NET_OPENING_HEIGHT = col_double(),
                HEAD_DEPTH = col_double(),
                `ESTIMATED_CATCHES_ BY_WT` = col_character(),
                PK_JUV = col_double(),
                CM_JUV = col_double(),
                CM_ADULT = col_double(),
                SE_JUV = col_double(),
                CO_JUV = col_double(),
                CK_JUV = col_double(),
                GEAR_TYPE = col_character(),
                COMMENTS = col_character()
              ))

# wrangle data for volume swept CPUE
salmondf <- salmondf_orig %>%
  mutate(DISTANCE_KM = DISTANCE * 1.852,
         WIDTH_KM = NET_OPENING_WIDTH/1000,
         HEIGHT_KM = NET_OPENING_HEIGHT/1000,
         MOUTH_KM2 = WIDTH_KM * HEIGHT_KM,
         VOLUME_KM3 = MOUTH_KM2 * DISTANCE_KM,
         PK_JUV_KM3 = PK_JUV/VOLUME_KM3,
         CM_JUV_KM3 = CM_JUV/VOLUME_KM3,
         SE_JUV_KM3 = SE_JUV/VOLUME_KM3,
         CO_JUV_KM3 = CO_JUV/VOLUME_KM3,
         CK_JUV_KM3 = CK_JUV/VOLUME_KM3)
              

```

```{r catch}

# # sql query
# SELECT STATION_INFO.CRUISE, BCSI_ECOSYSTEM_SPECIES_TOTALS.STATION_ID, BCSI_ECOSYSTEM_SPECIES_TOTALS.SPECIES_CODE, BCSI_ECOSYSTEM_SPECIES_TOTALS.SPECIES_COMMON_NAME, BCSI_ECOSYSTEM_SPECIES_TOTALS.PIECES, BCSI_ECOSYSTEM_SPECIES_TOTALS.WT
#  FROM (STATION_INFO INNER JOIN BCSI_ECOSYSTEM_SPECIES_TOTALS ON STATION_INFO.STATION_ID = BCSI_ECOSYSTEM_SPECIES_TOTALS.STATION_ID) INNER JOIN BRIDGE ON (BCSI_ECOSYSTEM_SPECIES_TOTALS.STATION_ID = BRIDGE.STATION_ID) AND (STATION_INFO.STATION_ID = BRIDGE.STATION_ID)
#  WHERE (((STATION_INFO.CRUISE)='2019125'))

catch_orig <- readr::read_csv("data/csv/2019125_catch_orig.csv",
                              col_types = cols(
  CRUISE = col_double(),
  STATION_ID = col_character(),
  SPECIES_CODE = col_character(),
  SPECIES_COMMON_NAME = col_character(),
  PIECES = col_double(),
  WT = col_double()
))

# upload GFBIO species table for common and scientific names
species_orig <- read_csv("data/csv/C_Species.csv",
                         col_types = cols(
  SPECIES_CODE = col_character(),
  SPECIES_DESC = col_character(),
  ROW_VERSION = col_double(),
  SPECIES_COMMON_NAME = col_character(),
  SPECIES_SCIENCE_NAME = col_character(),
  ITIS_TSN = col_double(),
  TAXONOMIC_RANK = col_character(),
  RSTY_ID = col_double(),
  PARENT_RSTY_ID = col_double(),
  PARENT_TAXONOMIC_UNIT = col_character(),
  SPECIES_GROUPING = col_character(),
  LSID = col_character()
))

# simiplify species table
species <- species_orig %>%
  select(SPECIES_CODE, SPECIES_COMMON_NAME, SPECIES_SCIENCE_NAME)

# pull mixed jelly/squid data out and remake to add seperate rows
mix <- catch_orig %>%
  filter(SPECIES_COMMON_NAME == "WATER JELLY/SQUID MIX")

# 50% assumption for mix
mixWT <- mix %>%
  pull(WT)
mixWT50 <- mixWT * 0.5

sepMix <- tibble(
  CRUISE = 2019125,
  STATION_ID = "BCSI-2019125-T02",
  SPECIES_CODE = c("3R5", "92D"),
  SPECIES_COMMON_NAME = c("WATER JELLY", "OPALESCENT SQUID"),
  PIECES = NA,
  WT = mixWT50)

# wrangle data
catch2 <- catch_orig %>%
  # omit any unusable tows; no aborted tows in 2019-125
  # remove salmon mix as idividual species are already listed
  filter(SPECIES_COMMON_NAME != "SALMON MIX") %>%
    filter(SPECIES_COMMON_NAME != "WATER JELLY/SQUID MIX")

# add seperate jelly and squid mix values
# remove when database back end is updated
catch3 <- rbind(sepMix, catch2)

catch4 <- catch3 %>%  
  # fix counts that are subsample (not total) from same station ***checked datasheets
  # ****remove once database back end updated
  mutate(PIECES2 = case_when(
    STATION_ID == "BCSI-2019125-QCST03" & SPECIES_CODE == "108J" ~ 284,
    STATION_ID == "BCSI-2019125-QCST03" & SPECIES_CODE == "112J" ~ 231,
    STATION_ID == "BCSI-2019125-QCST03" & SPECIES_CODE == "115J" ~ 9,
    STATION_ID == "BCSI-2019125-QCST03" & SPECIES_CODE == "118J" ~ 8,
    TRUE ~ PIECES)) %>%
  
# fix species codes where R dropped the 0 preceeding the code
  mutate(SPECIES_CODE = if_else(SPECIES_CODE != "96", as.character(SPECIES_CODE), "096")) %>%
  left_join(., species, by = "SPECIES_CODE") %>%
  mutate(DISPLAY_COMMON = if_else(is.na(SPECIES_COMMON_NAME.y), as.character(SPECIES_COMMON_NAME.x), SPECIES_COMMON_NAME.y)) %>%
  mutate(DISPLAY_COMMON = str_remove_all(DISPLAY_COMMON, "[()](JUVENILES)[)]*"),
         DISPLAY_COMMON = str_remove(DISPLAY_COMMON, "[()](ADULTS)[)]*"),
         DISPLAY_COMMON = if_else(DISPLAY_COMMON == "MOON JELLY", "MOON JELLYFISH", DISPLAY_COMMON),
         DISPLAY_COMMON = if_else(DISPLAY_COMMON == "WATER JELLY", "WATER JELLYFISH", DISPLAY_COMMON)) %>%
    mutate(COMMON_NAME = str_to_title(DISPLAY_COMMON),
         SCIENTIFIC_NAME = paste0(str_sub(SPECIES_SCIENCE_NAME, 1,1), str_sub(tolower(SPECIES_SCIENCE_NAME),2)))
  
catch <- catch4 %>%  
  group_by(COMMON_NAME, SCIENTIFIC_NAME) %>%
  summarise(numTows = n(),
            totalWgt = sum(WT, na.rm = TRUE),
            maxWgt = max(WT, na.rm = TRUE),
            meanWgt = round(mean(WT, na.rm = TRUE), 0)) %>%
  ungroup() %>%
  arrange(desc(totalWgt), desc(numTows)) %>%
  naniar::replace_with_na(replace = list(meanWgt = NaN, 
                                         maxWgt = -Inf, 
                                         totalWgt = 0)) 
```

```{r lengths}

# # sql query 2019125_lengthFreq2
# SELECT BRIDGE_COMPLETE.CRUISE, BIOLOGICAL_JUNCTION.FISH_NUMBER, BIOLOGICAL.DATE_CAPTURED, BIOLOGICAL.SPECIES, BIOLOGICAL.SHIP_FL, BIOLOGICAL.SHIP_SL, BIOLOGICAL.SHIP_TL, BIOLOGICAL.SHIP_ML, BIOLOGICAL.SHIP_BD, BIOLOGICAL.SHIP_WT
# FROM (BIOLOGICAL_JUNCTION INNER JOIN BRIDGE_COMPLETE ON BIOLOGICAL_JUNCTION.STATION_ID = BRIDGE_COMPLETE.STATION_ID) INNER JOIN BIOLOGICAL ON BIOLOGICAL_JUNCTION.FISH_NUMBER = BIOLOGICAL.FISH_NUMBER
# WHERE (((BRIDGE_COMPLETE.CRUISE)="2019125"));

lengthFreq_orig <- readr::read_csv("data/csv/2019125_lengthFreq.csv",
                                   col_types = cols(
  CRUISE = col_double(),
  FISH_NUMBER = col_character(),
  DATE_CAPTURED = col_character(), # Access and R date format conflict
  SPECIES = col_character(),
  SHIP_FL = col_double(),
  SHIP_SL = col_double(),
  SHIP_TL = col_double(),
  SHIP_ML = col_double(),
  SHIP_BD = col_double(),
  SHIP_WT = col_double()
))

# wrangle data
lengthFreq <- lengthFreq_orig %>%
  pivot_longer(., cols = c("SHIP_FL", "SHIP_SL", "SHIP_TL", "SHIP_ML", "SHIP_BD"),
               names_to = "LengthType",
               values_to = "LENGTH") %>%
  mutate( LOG.LEN = log(LENGTH),
         LOG.WT = log(SHIP_WT)) %>%
  rename(TRIP_ID = CRUISE,
         WEIGHT = SHIP_WT,
         COMMON_NAME = SPECIES)
```

```{r lengthweight}

lw_length <- lengthFreq %>%
  filter(!(is.na(LENGTH))) %>%
  separate(., FISH_NUMBER, into = c("Program", "Survey", "Station", "SPECIES_CODE", "FishNum")) %>%
  # group adult and juveniles together for this table
  mutate(COMMON_NAME = case_when(
    COMMON_NAME == "CHUM ADULT" ~ "CHUM",
    COMMON_NAME == "CHINOOK ADULT" ~ "CHINOOK",
    TRUE ~ COMMON_NAME)) %>%
  group_by(COMMON_NAME) %>%
  mutate(numTows = length(unique(Station))) %>%
  summarize(numTows = mean(numTows),            
            lengthNum = sum(!is.na(LENGTH)),
            minLen = min(LENGTH, na.rm = TRUE),
            maxLen = max(LENGTH, na.rm = TRUE),
            meanLen = round(mean(LENGTH, na.rm = TRUE), 0),
            .groups = "drop")

lw_weight <- lengthFreq %>%
  filter(!(is.na(LENGTH))) %>%
  filter(!(is.na(WEIGHT))) %>%
  # group adult and juveniles together for this table
  mutate(COMMON_NAME = case_when(
    COMMON_NAME == "CHUM ADULT" ~ "CHUM",
    COMMON_NAME == "CHINOOK ADULT" ~ "CHINOOK",
    TRUE ~ COMMON_NAME)) %>%
  group_by(COMMON_NAME) %>%
  summarize(wgtNum = sum(!is.na(WEIGHT)),
            minWgt = min(WEIGHT, na.rm = TRUE),
            maxWgt = max(WEIGHT, na.rm = TRUE),
            meanWGT = round(mean(WEIGHT, na.rm = TRUE), 0),
            .groups = "drop")

# join tables
lw <- lw_length %>%
  full_join(., lw_weight, by = "COMMON_NAME") %>%
  mutate(COMMON_NAME = str_to_title(COMMON_NAME),
         COMMON_NAME = case_when(
           COMMON_NAME == "Opalescent Squid" ~ "Opalescent Inshore Squid", 
           COMMON_NAME == "Chinook" ~ "Chinook Salmon",
           COMMON_NAME == "Pink" ~ "Pink Salmon",
           COMMON_NAME == "Sockeye" ~ "Sockeye Salmon",
           COMMON_NAME == "Coho" ~ "Coho Salmon",
           COMMON_NAME == "Chum" ~ "Chum Salmon",
           COMMON_NAME == "Herring" ~ "Pacific Herring",
           COMMON_NAME == "Aequorea" ~ "Water Jellyfish",
           COMMON_NAME == "Rock Sole" ~ "Flatfish",
           COMMON_NAME == "Moon Jelly" ~ "Moon Jellyfish",
           TRUE ~ COMMON_NAME)
         ) %>%
  arrange(-lengthNum)
```

```{r stomach}
# # sql query
# SELECT BRIDGE_COMPLETE.CRUISE, BIOLOGICAL.SPECIES, BCSI_STOMACH_CONTENTS.*
# FROM ((BIOLOGICAL_JUNCTION INNER JOIN BIOLOGICAL ON BIOLOGICAL_JUNCTION.FISH_NUMBER = BIOLOGICAL.FISH_NUMBER) INNER JOIN BCSI_STOMACH_CONTENTS ON BIOLOGICAL_JUNCTION.FISH_NUMBER = BCSI_STOMACH_CONTENTS.FISH_NUMBER) INNER JOIN BRIDGE_COMPLETE ON BIOLOGICAL_JUNCTION.STATION_ID = BRIDGE_COMPLETE.STATION_ID
# WHERE (((BRIDGE_COMPLETE.CRUISE)="2019125"));

# read csv 
stomachdf_orig <- readr::read_csv("data/csv/2019125_stomach_orig.csv",
                             col_types = cols(
  CRUISE = col_double(),
  SPECIES = col_character(),
  FISH_NUMBER = col_character(),
  `1-PREY_CODE` = col_character(),
  `1-VOLUME` = col_double(),
  `1-DIGESTION` = col_double(),
  `1-PREY_TRACES` = col_character(),
  `2-PREY_CODE` = col_character(),
  `2-VOLUME` = col_double(),
  `2-DIGESTON` = col_double(),
  `2-PREY_TRACES` = col_character(),
  `3-PREY_CODE` = col_character(),
  `3-VOLUME` = col_double(),
  `3-DIGESTION` = col_double(),
  `3-PREY_TRACES` = col_character(),
  COMMENTS = col_character()
))

# group adult and juveniles together
stomachdf_orig <- stomachdf_orig %>%
  mutate(SPECIES = case_when(
    SPECIES == "CHUM ADULT" ~ "CHUM",
    SPECIES == "CHINOOK ADULT" ~ "CHINOOK",
    TRUE ~ SPECIES))

# wrangle data
stomachTows <- stomachdf_orig %>%
  separate(., FISH_NUMBER, into = c("Program", "Survey", "Station", "SPECIES_CODE", "FishNum")) %>%
  group_by(SPECIES) %>%
  summarise(NumTows = length(unique(Station)))

stomachdf <- stomachdf_orig %>%
  group_by(SPECIES) %>%
  summarise(NumStomachs = length(`1-PREY_CODE`),
            NumEmpty = sum(`1-PREY_CODE` == "M002"),
            .groups = "drop") %>%
  mutate(PerEmpty = round((NumEmpty/NumStomachs)*100),0) %>%
  left_join(., stomachTows, by = "SPECIES")  %>%
  arrange(-NumTows) %>%
  mutate(COMMON_NAME = str_to_title(SPECIES),
         COMMON_NAME = case_when(
           COMMON_NAME == "Opalescent Squid" ~ "Opalescent Inshore Squid", 
           COMMON_NAME == "Chinook" ~ "Chinook Salmon",
           COMMON_NAME == "Pink" ~ "Pink Salmon",
           COMMON_NAME == "Sockeye" ~ "Sockeye Salmon",
           COMMON_NAME == "Coho" ~ "Coho Salmon",
           COMMON_NAME == "Chum" ~ "Chum Salmon",
           COMMON_NAME == "Herring" ~ "Pacific Herring",
           COMMON_NAME == "Aequorea" ~ "Water Jellyfish",
           COMMON_NAME == "Rock sole" ~ "Flatfish",
           TRUE ~ COMMON_NAME)) %>%
  select(COMMON_NAME, NumTows, NumStomachs, NumEmpty, PerEmpty)

```

```{r prey}

# wrangle stomach data
preycode <- stomachdf_orig %>%
  select(FISH_NUMBER, `1-PREY_CODE`, `2-PREY_CODE`, `3-PREY_CODE`) %>%
    pivot_longer(., cols = c("1-PREY_CODE", "2-PREY_CODE", "3-PREY_CODE"),
                 values_drop_na = TRUE, names_to = "PreyLevel", values_to = "PreySpecies") %>%
  mutate(Level = str_extract_all(PreyLevel, "[0-3]")
  )

volume <- stomachdf_orig %>%
  select(FISH_NUMBER, `1-VOLUME`, `2-VOLUME`, `3-VOLUME`) %>%
    pivot_longer(., cols = c("1-VOLUME", "2-VOLUME", "3-VOLUME"),
                 values_drop_na = TRUE, names_to = "VolLevel", values_to = "PreyVolume") %>%
  mutate(Level = str_extract_all(VolLevel, "[0-3]"))

# join together
prey <- preycode %>%
  full_join(., volume, by = c("FISH_NUMBER", "Level")) %>%
  filter(PreySpecies != "M002") %>% # empty code
  mutate(PreySpecies = if_else(PreySpecies == "96", "096", PreySpecies)) %>%
  separate(., FISH_NUMBER, into = c("Program", "Survey", "Station", "SPECIES_CODE", "FishNum")) %>%
  group_by(SPECIES_CODE, PreySpecies) %>%
  summarise(AvgVolume = round(mean(PreyVolume, na.rm = TRUE),2),
            NumPrey = length(PreyVolume),
            .groups = "drop") %>%
  left_join(., species, by = "SPECIES_CODE") %>%
  mutate(DISPLAY_COMMON = str_remove_all(SPECIES_COMMON_NAME, "[()](JUVENILES)[)]*"),
         DISPLAY_COMMON = str_remove(DISPLAY_COMMON, "[()](ADULTS)[)]*")
         ) %>%
  mutate(COMMON_NAME = str_to_title(DISPLAY_COMMON)) %>%
  select(COMMON_NAME, PreySpecies, AvgVolume, NumPrey) %>%
  left_join(., species, by = c("PreySpecies" = "SPECIES_CODE")) %>%
  mutate(PREY_NAME = case_when(
    PreySpecies == "M011" ~ "Unid. Remains",
    PreySpecies == "0A0" ~ "Invertebrate Remains",
    PreySpecies == "M010" ~ "Unid. Fishes",
    PreySpecies == "M014" ~ "Unid. Plankton",
    PreySpecies == "M004" ~ "Misc. Non-marine",
    PreySpecies == "OAB" ~ "Polychaetes",
    PreySpecies == "3B9" ~ "Pteropods",
    PreySpecies == "3X0" ~ "Ctenophores",
    PreySpecies == "3GO" ~ "Jellyfish(Scyphozoa)",
    PreySpecies == "MO11" ~ "Unid. Remains",
    TRUE ~ SPECIES_COMMON_NAME)) %>%
  select(COMMON_NAME, PREY_NAME, AvgVolume, NumPrey) %>%
  mutate(PREY_NAME = str_to_title(PREY_NAME)) %>%
  arrange(COMMON_NAME, -AvgVolume)

```

```{r bridge}

bridgetow_orig <- tows %>%
  mutate(Date = as.character(lubridate::ymd(str_c(YEAR, MONTH, DAY, sep = "-"))),
         # conver to DMS
         START_LAT_DMS = str_remove_all(deg2dms(START_LAT, "cat", " ", 0), "\\+"),
         START_LAT_DMS = str_c(str_sub(START_LAT_DMS,1,2), "\u00B0", " ",
         str_sub(START_LAT_DMS,4,5), "' ", str_sub(START_LAT_DMS,7,8), '" N'),
         END_LAT_DMS = str_remove_all(deg2dms(END_LAT, "cat", " ", 0), "\\+"),
         END_LAT_DMS = str_c(str_sub(END_LAT_DMS,1,2), "\u00B0", " ",
         str_sub(END_LAT_DMS,4,5), "' ", str_sub(END_LAT_DMS,7,8), '" N'),
         
         # LONG
        START_LONG_DMS = str_remove_all(deg2dms((START_LONG + 90), "cat", " ", 0), "-"),
         START_LONG_DMS =  str_c(as.character(as.numeric(str_sub(START_LONG_DMS,1,2)) + 90), "\u00B0", " ", str_sub(START_LONG_DMS,4,5), "' ", str_sub(START_LONG_DMS,7,8), '" W'),
        END_LONG_DMS = str_remove_all(deg2dms((END_LONG + 90), "cat", " ", 0), "-"),
         END_LONG_DMS =  str_c(as.character(as.numeric(str_sub(END_LONG_DMS,1,2)) + 90), "\u00B0", " ", str_sub(END_LONG_DMS,4,5), "' ", str_sub(END_LONG_DMS,7,8), '" W')) %>%
  
  mutate(DURATION = round(DUR * 60, 0), # from hours to minutes
         SPEED_KM = round(`SOG-KTS`*1.852,1),
         DISTANCE_KM = round(DISTANCE * 1.852, 2),
         START_TIME_hm = str_pad(str_extract(str_extract(START_TIME, "[0-9]+[\\:][0-9]+[\\:][0-9]+$"), "^[0-9]+[\\:][0-9]+"), 5, "left", "0"),
         Usable = if_else(UNUSABLE == FALSE, "Y", "N"),
         SPEED_NM = `SOG-KTS`) %>%
  
  select(EVENT, Date, STATION, GEAR, START_TIME_hm, DURATION, START_LAT_DMS, START_LONG_DMS, END_LAT_DMS, END_LONG_DMS, HEADING, SPEED_KM, SPEED_NM, DISTANCE_KM, NET_OPENING_WIDTH, NET_OPENING_HEIGHT, WARP, TARGET_DEPTH, START_BOT_DEPTH, END_BOT_DEPTH, Usable)

bridgetow <- bridgetow_orig %>%
  select(-SPEED_NM) %>%
    dplyr::rename(
         "Event Number" = EVENT,
         "Station ID" = STATION,
         "Net" = GEAR,
         "Start Time (PDT)" = START_TIME_hm,
         "Duration (min)" = DURATION,
         "Start Latitude" = START_LAT_DMS,
         "Start Longitude" = START_LONG_DMS,
         "End Latitude" = END_LAT_DMS,
         "End Longitude" = END_LONG_DMS,
         "Direction of Tow (deg)" = HEADING,
         "Vessel Speed (km/h)" = SPEED_KM,
         "Distance Towed (km)" = DISTANCE_KM,
         "Net Opening Height (m)" = NET_OPENING_HEIGHT,
         "Net Opening Width (m)" = NET_OPENING_WIDTH,
         "Warp Length (m)" = WARP,
         #"Door Spread (m)" = Doorspread,
         "Target Headrope Depth (m)" = TARGET_DEPTH,
         "Start Bottom Depth (m)" = START_BOT_DEPTH,
         "End Bottom Depth (m)" = END_BOT_DEPTH)

# get target depth specific min and max warp
minWarp0 <- bridgetow %>%
  filter(`Target Headrope Depth (m)` == 0) %>%
  summarize(minWarp = min(`Warp Length (m)`, na.rm = TRUE)) %>%
  pull(minWarp)

minWarp15 <- bridgetow %>%
  filter(`Target Headrope Depth (m)` == 15) %>%
  summarize(minWarp = min(`Warp Length (m)`, na.rm = TRUE)) %>%
  pull(minWarp)

maxWarp0 <- bridgetow %>%
  filter(`Target Headrope Depth (m)` == 0) %>%
  summarize(maxWarp = max(`Warp Length (m)`, na.rm = TRUE)) %>%
  pull(maxWarp)

maxWarp15 <- bridgetow %>%
  filter(`Target Headrope Depth (m)` == 15) %>%
  summarize(maxWarp = max(`Warp Length (m)`, na.rm = TRUE)) %>%
  pull(maxWarp)
# on this survey it overlap completing so use overall warp


# transpose table into display format
# tows as column names
bridge_t <- as.data.frame(t(bridgetow))

# column names as vector
col_from <- colnames(bridge_t)

# column names from tow number
col_to <- 1:nrow(bridgetow)

# rename column names with consequtive tow number
bridge_t <- bridge_t %>%
  rename_at(vars(col_from), function(x) col_to)

# make vector for row names
MeasurementNames <- as.vector(row.names(bridge_t))
  
# make function to create discrete tables for display
breakBridgeTable <- function(df, rowNum, MeasurementNames) {
  
  df <- bridge_t %>%
    select(rowNum) %>%  
    mutate(`Tow Number` = MeasurementNames) %>%
    select(`Tow Number`, everything())
    
}

# divide the total tows by 3 to make discrete tables
bridge1 <- breakBridgeTable(bridge_t, 1:6, MeasurementNames)
bridge2 <- breakBridgeTable(bridge_t, 7:13, MeasurementNames)
bridge3 <- breakBridgeTable(bridge_t, 14:20, MeasurementNames)
bridge4 <- breakBridgeTable(bridge_t, 21:27, MeasurementNames)
bridge5 <- breakBridgeTable(bridge_t, 28:34, MeasurementNames)
bridge6 <- breakBridgeTable(bridge_t, 35:37, MeasurementNames)

```

```{r CTDdepthtime}

# date, start time, bottom depth, gear depth for CTD, Bongo Vert
# for this version include start lat/long and end lat/long

ocean_wider <- ctd_orig %>%
  full_join(., plankton_orig, by = c("CRUISE","STATION_ID")) %>%
  mutate(DATE_PT = as.character(mdy(str_extract(DATE, "\\d{2}/[0-9]+/[0-9]+"))),
         BONGO_START_TIME_hm = str_pad(str_extract(str_extract(START_TIME_BONGO, "[0-9]+[\\:][0-9]+[\\:][0-9]+$"), "^[0-9]+[\\:][0-9]+"), 5, "left", "0"),
         CTD_START_UTC = mdy_hms(TIME_UTC, tz = "UTC"),
         CTD_START_PT = with_tz(CTD_START_UTC, "America/Los_Angeles"),
         CTD_START_TIME_hm = str_pad(str_extract(str_extract(CTD_START_PT, "[0-9]+[\\:][0-9]+[\\:][0-9]+$"), "^[0-9]+[\\:][0-9]+"), 5, "left", "0"),
         BONGO_DEPTH = if_else(is.na(RBR_DEPTH), TARGET_DEPTH, RBR_DEPTH)) %>%
  # make decimal degrees into DMS
mutate(CTD_LAT_DMS = str_remove_all(deg2dms(CTD_LAT, "cat", " ", 0), "\\+"),
         CTD_LAT_DMS = str_c(str_sub(CTD_LAT_DMS,1,2), "\u00B0", " ",
         str_sub(CTD_LAT_DMS,4,5), "' ", str_sub(CTD_LAT_DMS,7,8), '" N'),
         BONGO_LAT_DMS = str_remove_all(deg2dms(BONGO_LAT, "cat", " ", 0), "\\+"),
         BONGO_LAT_DMS = str_c(str_sub(BONGO_LAT_DMS,1,2), "\u00B0", " ",
         str_sub(BONGO_LAT_DMS,4,5), "' ", str_sub(BONGO_LAT_DMS,7,8), '" N'),
         
         # LONG
        CTD_LONG_DMS = str_remove_all(deg2dms((CTD_LONG + 90), "cat", " ", 0), "-"),
         CTD_LONG_DMS =  str_c(as.character(as.numeric(str_sub(CTD_LONG_DMS,1,2)) + 90), "\u00B0", " ", str_sub(CTD_LONG_DMS,4,5), "' ", str_sub(CTD_LONG_DMS,7,8), '" W'),
        BONGO_LONG_DMS = str_remove_all(deg2dms((BONGO_LONG + 90), "cat", " ", 0), "-"),
         BONGO_LONG_DMS =  str_c(as.character(as.numeric(str_sub(BONGO_LONG_DMS,1,2)) + 90), "\u00B0", " ", str_sub(BONGO_LONG_DMS,4,5), "' ", str_sub(BONGO_LONG_DMS,7,8), '" W')) %>%
  
  select(DATE_PT, STATION, CTD_LAT_DMS, CTD_LONG_DMS, CTD_START_TIME_hm, BOTTOM_DEPTH, CTD_DEPTH, BONGO_LAT_DMS, BONGO_LONG_DMS, BONGO_START_TIME_hm, BOT_DEPTH, BONGO_DEPTH)

```

```{r catchAppendix}

# find event numbers to join by station
stations <- tows %>%
  select(EVENT, STATION_ID)

# find any unusable tows for catch data
removeStations <- bridgetow %>%
  filter(Usable == "N") %>%
  pull(`Station ID`)

# wrangle catch data
catchApp <- catch4 %>%
  # omit any unusable tows
  filter(!(STATION_ID %in% removeStations)) %>%
  left_join(., stations, by = "STATION_ID") %>%
  select(COMMON_NAME, EVENT, WT) %>%
  group_by(COMMON_NAME, EVENT) %>%
  summarize(WT_total = sum(WT, na.rm = TRUE), 
            .groups = "drop") %>%
  # use kg for this table
  mutate(WT_KG = round(WT_total/ 1000,2)) %>%
  select(-WT_total) %>%
  filter(!(is.na(WT_KG))) %>%
  dplyr::rename(`Event Number` = EVENT)

catch_spread <- catchApp %>%
  pivot_wider(., names_from = `Event Number`, values_from = WT_KG) %>%
  arrange(COMMON_NAME) 

# make vector for species names
speciesNames <- as.vector(catch_spread$COMMON_NAME)

# make function to create discrete tables for displaying catch
# and summary total to bottom row
breakcatchTable <- function(colNum, speciesNames, catch_spread) {
  
  df <- catch_spread %>%
  select(-COMMON_NAME) %>%
    select(colNum) %>%
    mutate(`Event Number` = str_to_title(as.character(speciesNames))) %>%
    select(`Event Number`, everything())
  
  # create summary totals
summaryfunc <- function(z) if (is.numeric(z)) sum(z, na.rm = TRUE) else ''
sumrow <- as.data.frame(lapply(df, summaryfunc))
sumrow$Event.Number <- as.character(sumrow$Event.Number)
sumrow[1,1] <- "TOTAL" # *** need to add if else to leave unusable tows as - here

# create vector of column names to match
colNamesdf <- colnames(df)
colnames(sumrow) <- colNamesdf

df <- rbind(df, sumrow)
}

# these column numbers need to be modified in appendix catchTable section if they change
catchApp1 <- breakcatchTable(1:11, speciesNames, catch_spread)
catchApp2 <- breakcatchTable(12:22, speciesNames, catch_spread)
catchApp3 <- breakcatchTable(23:33, speciesNames, catch_spread)
catchApp4 <- breakcatchTable(34:37, speciesNames, catch_spread)

```

